// A curated subset of Whisper's supported languages, ordered by rough
// global usage. Values are the language names Whisper's tokenizer expects.
// "auto" (handled in the UI) lets Whisper detect the language itself.
export const LANGUAGES = [
  ['english', 'English'],
  ['chinese', 'Chinese'],
  ['german', 'German'],
  ['spanish', 'Spanish'],
  ['russian', 'Russian'],
  ['french', 'French'],
  ['portuguese', 'Portuguese'],
  ['japanese', 'Japanese'],
  ['korean', 'Korean'],
  ['italian', 'Italian'],
  ['dutch', 'Dutch'],
  ['turkish', 'Turkish'],
  ['polish', 'Polish'],
  ['arabic', 'Arabic'],
  ['hindi', 'Hindi'],
  ['ukrainian', 'Ukrainian'],
  ['swedish', 'Swedish'],
  ['czech', 'Czech'],
  ['greek', 'Greek'],
  ['hebrew', 'Hebrew'],
  ['danish', 'Danish'],
  ['finnish', 'Finnish'],
  ['norwegian', 'Norwegian'],
  ['romanian', 'Romanian'],
  ['hungarian', 'Hungarian'],
  ['indonesian', 'Indonesian'],
  ['vietnamese', 'Vietnamese'],
  ['thai', 'Thai'],
  ['catalan', 'Catalan'],
];
